apiVersion: v1
kind: Service
metadata:
  name: node-app-service-prod
  namespace: prod
spec:
  selector:
    app: node-app-prod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: NodePort
