apiVersion: v1
kind: Service
metadata:
  name: node-app-service-stage
  namespace: stage
spec:
  selector:
    app: node-app-stage
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: NodePort
